//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1022
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Founder.PKURG.EPM.Test.EPMServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EPMServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 blockName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateProjectApproval", ReplyAction="*")]
        Founder.PKURG.EPM.Test.EPMServiceReference.CreateProjectApprovalResponse CreateProjectApproval(Founder.PKURG.EPM.Test.EPMServiceReference.CreateProjectApprovalRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 approvalPerson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpDateProjectApproval", ReplyAction="*")]
        Founder.PKURG.EPM.Test.EPMServiceReference.UpDateProjectApprovalResponse UpDateProjectApproval(Founder.PKURG.EPM.Test.EPMServiceReference.UpDateProjectApprovalRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateProjectApprovalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateProjectApproval", Namespace="http://tempuri.org/", Order=0)]
        public Founder.PKURG.EPM.Test.EPMServiceReference.CreateProjectApprovalRequestBody Body;
        
        public CreateProjectApprovalRequest() {
        }
        
        public CreateProjectApprovalRequest(Founder.PKURG.EPM.Test.EPMServiceReference.CreateProjectApprovalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateProjectApprovalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid projectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long itemname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string blockName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string approvalPerson;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string oa;
        
        public CreateProjectApprovalRequestBody() {
        }
        
        public CreateProjectApprovalRequestBody(System.Guid projectId, long itemname, string blockName, string approvalPerson, string oa) {
            this.projectId = projectId;
            this.itemname = itemname;
            this.blockName = blockName;
            this.approvalPerson = approvalPerson;
            this.oa = oa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateProjectApprovalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateProjectApprovalResponse", Namespace="http://tempuri.org/", Order=0)]
        public Founder.PKURG.EPM.Test.EPMServiceReference.CreateProjectApprovalResponseBody Body;
        
        public CreateProjectApprovalResponse() {
        }
        
        public CreateProjectApprovalResponse(Founder.PKURG.EPM.Test.EPMServiceReference.CreateProjectApprovalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateProjectApprovalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid CreateProjectApprovalResult;
        
        public CreateProjectApprovalResponseBody() {
        }
        
        public CreateProjectApprovalResponseBody(System.Guid CreateProjectApprovalResult) {
            this.CreateProjectApprovalResult = CreateProjectApprovalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpDateProjectApprovalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpDateProjectApproval", Namespace="http://tempuri.org/", Order=0)]
        public Founder.PKURG.EPM.Test.EPMServiceReference.UpDateProjectApprovalRequestBody Body;
        
        public UpDateProjectApprovalRequest() {
        }
        
        public UpDateProjectApprovalRequest(Founder.PKURG.EPM.Test.EPMServiceReference.UpDateProjectApprovalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpDateProjectApprovalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string approvalPerson;
        
        public UpDateProjectApprovalRequestBody() {
        }
        
        public UpDateProjectApprovalRequestBody(System.Guid id, int status, string approvalPerson) {
            this.id = id;
            this.status = status;
            this.approvalPerson = approvalPerson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpDateProjectApprovalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpDateProjectApprovalResponse", Namespace="http://tempuri.org/", Order=0)]
        public Founder.PKURG.EPM.Test.EPMServiceReference.UpDateProjectApprovalResponseBody Body;
        
        public UpDateProjectApprovalResponse() {
        }
        
        public UpDateProjectApprovalResponse(Founder.PKURG.EPM.Test.EPMServiceReference.UpDateProjectApprovalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpDateProjectApprovalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpDateProjectApprovalResult;
        
        public UpDateProjectApprovalResponseBody() {
        }
        
        public UpDateProjectApprovalResponseBody(bool UpDateProjectApprovalResult) {
            this.UpDateProjectApprovalResult = UpDateProjectApprovalResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Founder.PKURG.EPM.Test.EPMServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Founder.PKURG.EPM.Test.EPMServiceReference.WebServiceSoap>, Founder.PKURG.EPM.Test.EPMServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Founder.PKURG.EPM.Test.EPMServiceReference.CreateProjectApprovalResponse Founder.PKURG.EPM.Test.EPMServiceReference.WebServiceSoap.CreateProjectApproval(Founder.PKURG.EPM.Test.EPMServiceReference.CreateProjectApprovalRequest request) {
            return base.Channel.CreateProjectApproval(request);
        }
        
        public System.Guid CreateProjectApproval(System.Guid projectId, long itemname, string blockName, string approvalPerson, string oa) {
            Founder.PKURG.EPM.Test.EPMServiceReference.CreateProjectApprovalRequest inValue = new Founder.PKURG.EPM.Test.EPMServiceReference.CreateProjectApprovalRequest();
            inValue.Body = new Founder.PKURG.EPM.Test.EPMServiceReference.CreateProjectApprovalRequestBody();
            inValue.Body.projectId = projectId;
            inValue.Body.itemname = itemname;
            inValue.Body.blockName = blockName;
            inValue.Body.approvalPerson = approvalPerson;
            inValue.Body.oa = oa;
            Founder.PKURG.EPM.Test.EPMServiceReference.CreateProjectApprovalResponse retVal = ((Founder.PKURG.EPM.Test.EPMServiceReference.WebServiceSoap)(this)).CreateProjectApproval(inValue);
            return retVal.Body.CreateProjectApprovalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Founder.PKURG.EPM.Test.EPMServiceReference.UpDateProjectApprovalResponse Founder.PKURG.EPM.Test.EPMServiceReference.WebServiceSoap.UpDateProjectApproval(Founder.PKURG.EPM.Test.EPMServiceReference.UpDateProjectApprovalRequest request) {
            return base.Channel.UpDateProjectApproval(request);
        }
        
        public bool UpDateProjectApproval(System.Guid id, int status, string approvalPerson) {
            Founder.PKURG.EPM.Test.EPMServiceReference.UpDateProjectApprovalRequest inValue = new Founder.PKURG.EPM.Test.EPMServiceReference.UpDateProjectApprovalRequest();
            inValue.Body = new Founder.PKURG.EPM.Test.EPMServiceReference.UpDateProjectApprovalRequestBody();
            inValue.Body.id = id;
            inValue.Body.status = status;
            inValue.Body.approvalPerson = approvalPerson;
            Founder.PKURG.EPM.Test.EPMServiceReference.UpDateProjectApprovalResponse retVal = ((Founder.PKURG.EPM.Test.EPMServiceReference.WebServiceSoap)(this)).UpDateProjectApproval(inValue);
            return retVal.Body.UpDateProjectApprovalResult;
        }
    }
}
